### ISSUE TITLE
Add Comonad Instances

### ISSUE THREAD

**Issue by ChrisPenner** [NorfairKing/cursor#11]
Not sure if you're open to adding `comonads` as a dependency, but it'd be great to have comonad instances for all the applicable types; would probably be a good Hacktoberfest issue if you're open to it 😄

**Comment by NorfairKing** [comment]
@ChrisPenner Thanks for the interest! What would you use this instance for? I've had multiple people talk to me about `NonEmptyCursor` being a comonad but no one has pointed me to a practical application of this fact yet, so I haven't bothered to implement the instance.

**Comment by ChrisPenner** [comment]
Ah; good point about the parameter order, that makes this tricky then I suppose.

No worries 😄
